### ISSUE TITLE
Feature roadmap

### ISSUE THREAD

**Issue by rszamszur** [rszamszur/fastapi-mvc#53]
# Roadmap

Hello there! :wave:

This is the roadmap for fastapi-mvc, which gives an overview of future features and ideas that will be implemented. If you want to contribute with new ideas, feel free to submit a feature request. You can also develop the ones that are listed. For more information please see [contributing guidelines](https://github.com/rszamszur/fastapi-mvc/blob/master/CONTRIBUTING.md).

This roadmap is subject to change and features will be added as needed. 

## Checklist

- [ ] Initial project template.
    - [ ] Implement FastAPI application core with unit tests.
    - [ ] Add [Poetry](https://github.com/python-poetry/poetry) for dependency management and packaging.
    - [ ] Add virtualized development environment.
    - [ ] Add Makefile.
    - [ ] Add Helm chart.
    - [ ] Add Aiohttp and Redis utilities.
    - [ ] Add Redis support.
    - [ ] Add make target for bootstrapping a local minikube cluster with High Availability Redis cluster, and deploy the application.
- [ ] Add GitHub actions automation.
- [ ] Add documentation #9 
- [ ] Refactor project from the pure template into the package which generates fastapi-mvc projects from cookiecutter template #6 
- [ ] Improve Dockerfile for production use #15 #16 
- [ ] Implement CLI fastapi-mvc run command for running uvicorn development server #14 #31 
- [ ] Add initial generators implementation
    - [ ] Controller generator #47 
    - [ ] Model generator #45 
- [ ] Integrate databases support #46 
    - [ ] PostgreSQL
    - [ ] MySQL
    - [ ] SQLite
- [ ] Add databases HA deployments to script for bootstrapping application stack in Kubernetes cluster.
    - [ ] PostgreSQL
    - [x] Redis
- [ ] Add support for structured logging - Implement SEQ logging handler #26
